//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTO_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int chatId { get; set; }
        public long senderId { get; set; }
        public long receiverId { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public bool status { get; set; }
    }
}
