//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTO_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTOEntities : DbContext
    {
        public CTOEntities()
            : base("name=CTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<day> days { get; set; }
        public virtual DbSet<deleted_groups> deleted_groups { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<email_status> email_status { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<request_period> request_period { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<temp_requests> temp_requests { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
        public virtual DbSet<verified_requests> verified_requests { get; set; }
    }
}
