//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTO_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_status
    {
        public int requestId { get; set; }
        public long studentId { get; set; }
        public bool status { get; set; }
        public System.Guid activationCode { get; set; }
    
        public virtual student student { get; set; }
        public virtual temp_requests temp_requests { get; set; }
    }
}
