//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTO_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public temp_requests()
        {
            this.email_status = new HashSet<email_status>();
        }
    
        public int id { get; set; }
        public long stidentIdOne { get; set; }
        public long studentIdTwo { get; set; }
        public Nullable<long> studentIdThree { get; set; }
        public Nullable<long> studentIdFour { get; set; }
        public Nullable<long> studendIdFive { get; set; }
        public Nullable<long> studentIdSix { get; set; }
        public int courseId { get; set; }
        public string note { get; set; }
    
        public virtual cours cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email_status> email_status { get; set; }
        public virtual student student { get; set; }
        public virtual student student1 { get; set; }
        public virtual student student2 { get; set; }
        public virtual student student3 { get; set; }
        public virtual student student4 { get; set; }
        public virtual student student5 { get; set; }
        public virtual verified_requests verified_requests { get; set; }
    }
}
