//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTO_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class verified_requests
    {
        public int id { get; set; }
        public long studentIdOne { get; set; }
        public long studentIdTwo { get; set; }
        public Nullable<long> studentIdThree { get; set; }
        public Nullable<long> studentIdFour { get; set; }
        public Nullable<long> studentIdFive { get; set; }
        public Nullable<long> studentIdSix { get; set; }
        public int courseId { get; set; }
        public string note { get; set; }
        public bool approved { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual student student { get; set; }
        public virtual student student1 { get; set; }
        public virtual student student2 { get; set; }
        public virtual student student3 { get; set; }
        public virtual student student4 { get; set; }
        public virtual student student5 { get; set; }
        public virtual temp_requests temp_requests { get; set; }
    }
}
